Desktop version
mohamed20163858/my-portfolio pull request #6
Opened 2022-07-07 19:54 UTC by mohamed20163858

2022-07-07 21:34 UTC, wuletawwonte requested changes
# Hi @mohamed20163858  👋🏿👋🏿👋🏿  

Good job so far!
There are some issues that you still need to work on to go to the next project! You have only a few more steps and you are done! 💪 💪 💪 

![giphy](https://user-images.githubusercontent.com/74506933/153382064-ed760a8c-4f4a-48d6-b1f0-1aa9e5135097.gif)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Nice commit history ✔️
- Well structured files ✔️ 

## Required Changes ♻️
_Please check the comments under the review as well._

- [ ] Please add a description to your pull request. You can list what changes you made in this pull request. 
- [x] For a viewport width between 768px and 1000px your website scrolls horizontally. That's because you have got a content wider than the size of the viewport. Please try to avoid a horizontal scroll by setting the width of your elements using `vw` and `%`. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-08 13:58 UTC, mohamed20163858 commented on index.html
> +                <img src="images/crytalUPDesktop.png" alt="crystal-up-icon" class="crytal-1-desktop">
@wuletawwonte thanks a lot man i fixed it and the implementation was really awesome with it

2022-07-08 13:58 UTC, mohamed20163858 commented on css/main.css
> +    width: 920px;
@wuletawwonte yes i do it and it helped me a lot to make my website more responsive thanks to you to mention that to me thanks a lot

2022-07-08 14:54 UTC, omarsalem7 approved these changes
Hi @mohamed20163858 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ No linter errors. 
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 15:19 UTC, merged